% 1: desc a
% 2: desc b
% 3: desc c
% 4: desc d
% 5: spar a
% 6: spar b
% 7: spar c
% 8: spar d
% 9: full a
% 10: full b
% 11: full c
% 12: full d
pert = {'a','b','c','d'};
ctrl = {'Desc','Spar','Full'};

IAE_indv = X(:, [2:5]); 
% Reorganizar en [salida x controlador]
% columnas: [y1 y2 y3 y4]
% filas: [ Desc Spar Full ]
% IAE_pert_a = [ ...
%     IAE_indv(1,[1 5 9]), ...   % 1ra COLUMNA: y1 
%     IAE_indv(2,[1 5 9]), ...   % 2da
%     IAE_indv(3,[1 5 9]), ...   % 3ra
%     IAE_indv(4,[1 5 9]);]      % 4ta
% IAE_pert_b = [ ...
%     IAE_indv(1,[1 5 9]+1), ...   % 1ra COLUMNA: y1 
%     IAE_indv(2,[1 5 9]+1), ...   % 2da
%     IAE_indv(3,[1 5 9]+1), ...   % 3ra
%     IAE_indv(4,[1 5 9]+1);]      % 4ta
% IAE_pert_c = [ ...
%     IAE_indv(1,[1 5 9]+2), ...   % 1ra COLUMNA: y1 
%     IAE_indv(2,[1 5 9]+2), ...   % 2da
%     IAE_indv(3,[1 5 9]+2), ...   % 3ra
%     IAE_indv(4,[1 5 9]+2);]      % 4ta
% IAE_pert_d = [ ...
%     IAE_indv(1,[1 5 9]+3), ...   % 1ra COLUMNA: y1 
%     IAE_indv(2,[1 5 9]+3), ...   % 2da
%     IAE_indv(3,[1 5 9]+3), ...   % 3ra
%     IAE_indv(4,[1 5 9]+3);]      % 4ta

rows      = 1:4;
baseCols  = [1 5 9];
offsets   = 0:3;
IAE_pert = cell(1, numel(offsets));
for k = 1:numel(offsets)
    IAE_pert{k} = IAE_indv(baseCols + offsets(k), rows)
end
% unpacking
[IAE_pert_a, IAE_pert_b, IAE_pert_c, IAE_pert_d] = IAE_pert{:};

 T_IAE_a = table( ...
    ctrl', ...
    IAE_pert_a(:,1), ...
    IAE_pert_a(:,2), ...
    IAE_pert_a(:,3), ...
    IAE_pert_a(:,4), ...    
    'VariableNames', {'Ctrl','Th_out_1 (y1)','Th_out_2 (y2)','Tc_out_1 (y3)','Tc_out_2 (y4)'})
 T_IAE_b = table( ...
    ctrl', ...
    IAE_pert_b(:,1), ...
    IAE_pert_b(:,2), ...
    IAE_pert_b(:,3), ...
    IAE_pert_b(:,4), ...    
    'VariableNames', {'Ctrl','Th_out_1 (y1)','Th_out_2 (y2)','Tc_out_1 (y3)','Tc_out_2 (y4)'})
 T_IAE_c = table( ...
    ctrl', ...
    IAE_pert_c(:,1), ...
    IAE_pert_c(:,2), ...
    IAE_pert_c(:,3), ...
    IAE_pert_c(:,4), ...    
    'VariableNames', {'Ctrl','Th_out_1 (y1)','Th_out_2 (y2)','Tc_out_1 (y3)','Tc_out_2 (y4)'})
 T_IAE_d = table( ...
    ctrl', ...
    IAE_pert_d(:,1), ...
    IAE_pert_d(:,2), ...
    IAE_pert_d(:,3), ...
    IAE_pert_d(:,4), ...   
    'VariableNames', {'Ctrl','Th_out_1 (y1)','Th_out_2 (y2)','Tc_out_1 (y3)','Tc_out_2 (y4)'})

writetable(T_IAE_a, 'tabla_RIC_IAE.xlsx', 'Sheet', 'IAE_pert_a')
writetable(T_IAE_b, 'tabla_RIC_IAE.xlsx', 'Sheet', 'IAE_pert_b')
writetable(T_IAE_c, 'tabla_RIC_IAE.xlsx', 'Sheet', 'IAE_pert_c')
writetable(T_IAE_d, 'tabla_RIC_IAE.xlsx', 'Sheet', 'IAE_pert_d')

%% Eu
if RIC==6
    casos_pert = {'a','b','c','d'};
    ctrl = {'Desc','Spar','Full'};

    % Eu_indv: 12 filas, 4 columnas
    % filas = [desc_a,desc_b,desc_c,desc_d, spar_a,spar_b,spar_c,spar_d, full_a,full_b,full_c,full_d]
    % cols  = [eu1 eu2 eu3 eu4]
    Eu_indv = Y(:, 2:5);

    % Reorganizar en [v.m. x controlador]
    % columnas: [Byp2  Byp3  Byp8  Utilidad1  Utilidad2  Utilidad3]  ---> 6 columnas
    % filas:    [Desc; Spar; Full]

    % --- caso 'a' (offset 0)
    Eu_pert_a = [ ...
        [Eu_indv(1,1); nan;          Eu_indv(9,1)], ...   % Byp2  (Desc y1) / (Full y1)
        [nan;          Eu_indv(5,1); nan], ...            % Byp3  (Spar y1)
        [nan;          Eu_indv(5,2); Eu_indv(9,2)], ...   % Byp8  (Spar y2) / (Full y2)
        [Eu_indv(1,2); Eu_indv(5,3); Eu_indv(9,3)], ...   % Ut1   (Desc y2) / (Spar y3) / (Full y3)
        [Eu_indv(1,3); Eu_indv(5,4); Eu_indv(9,4)], ...   % Ut2   (Desc y3) / (Spar y4) / (Full y4)
        [Eu_indv(1,4); nan;          nan] ...             % Ut3   (Desc y4)
    ];

    % Indices base para el caso 'a'
    rDesc0 = 1;   % desc_a
    rSpar0 = 5;   % spar_a
    rFull0 = 9;   % full_a

    % Generador: k = 0,1,2,3 para a,b,c,d
    mkEuPert = @(k) [ ...
        [Eu_indv(rDesc0+k,1); nan;               Eu_indv(rFull0+k,1)], ... % Byp2
        [nan;               Eu_indv(rSpar0+k,1); nan], ...                % Byp3
        [nan;               Eu_indv(rSpar0+k,2); Eu_indv(rFull0+k,2)], ... % Byp8
        [Eu_indv(rDesc0+k,2); Eu_indv(rSpar0+k,3); Eu_indv(rFull0+k,3)], ... % Ut1
        [Eu_indv(rDesc0+k,3); Eu_indv(rSpar0+k,4); Eu_indv(rFull0+k,4)], ... % Ut2
        [Eu_indv(rDesc0+k,4); nan;               nan] ...                 % Ut3
    ];

    Eu_pert_b = mkEuPert(1);
    Eu_pert_c = mkEuPert(2);
    Eu_pert_d = mkEuPert(3);

    % Tablas
    varNames = {'Ctrl','u2','u3','u8','fcu1','fcu2','fhu2'};

    T_Eu_a = table( ...
        ctrl', ...
        Eu_pert_a(:,1), Eu_pert_a(:,2), Eu_pert_a(:,3), Eu_pert_a(:,4), Eu_pert_a(:,5), Eu_pert_a(:,6), ...
        'VariableNames', varNames)

    T_Eu_b = table( ...
        ctrl', ...
        Eu_pert_b(:,1), Eu_pert_b(:,2), Eu_pert_b(:,3), Eu_pert_b(:,4), Eu_pert_b(:,5), Eu_pert_b(:,6), ...
        'VariableNames', varNames)

    T_Eu_c = table( ...
        ctrl', ...
        Eu_pert_c(:,1), Eu_pert_c(:,2), Eu_pert_c(:,3), Eu_pert_c(:,4), Eu_pert_c(:,5), Eu_pert_c(:,6), ...
        'VariableNames', varNames)

    T_Eu_d = table( ...
        ctrl', ...
        Eu_pert_d(:,1), Eu_pert_d(:,2), Eu_pert_d(:,3), Eu_pert_d(:,4), Eu_pert_d(:,5), Eu_pert_d(:,6), ...
        'VariableNames', varNames)

end


if RIC==7
casos_pert = {'a','b','c','d'};
ctrl = {'Desc','Spar','Full'};
						%1      2      3      4      5      6      7     8      9      10      11     12
Eu_indv = Y(:, [2:5]); % 12 filas, 4 columnas [desc_a,desc_b,desc_c,desc_d,spar_a,spar_b,spar_c,spar_d,full_a,full_b,full_c,full_d] x [eu1 eu2 eu3 eu4] 
% Reorganizar en [v.m. x controlador]
% columnas: [Byp 2	Byp 5	Byp 8	Utilidad 1	Utilidad 2	Utilidad 3] % ---> 6 columnas
% filas: [ Desc Spar Full ]

%---
Eu_pert_a = [ ...
    [nan; nan; Eu_indv(9,1)], ...                 	% byp2  -> (full_a, eu1)
    [nan; Eu_indv(5,1); nan], ...                 	% byp5  -> (spar_a, eu1)
    [Eu_indv(1,1); nan; Eu_indv(9,2)], ...        	% byp8  -> (desc_a, eu1) ; (full_a, eu2)
    [Eu_indv(1,2); Eu_indv(5,2); Eu_indv(9,3)],...	% ut1   -> (desc_a, eu2) ; (spar_a, eu2) ; (full_a, eu3)
    [Eu_indv(1,3); Eu_indv(5,3); Eu_indv(9,4)],...	% ut2   -> (desc_a, eu3) ; (spar_a, eu3) ; (full_a, eu4)
    [Eu_indv(1,4); Eu_indv(5,4); nan] ...         	% ut3   -> (desc_a, eu4) ; (spar_a, eu4)
];

% Eu_indv: 12x4, filas = [desc_a..d, spar_a..d, full_a..d]
% indices base para el caso 'a':
rDesc0 = 1;   % desc_a
rSpar0 = 5;   % spar_a
rFull0 = 9;   % full_a

mkEuPert = @(k) [ ...
    [nan; nan; Eu_indv(rFull0+k, 1)], ...                         % byp2
    [nan; Eu_indv(rSpar0+k, 1); nan], ...                         % byp5
    [Eu_indv(rDesc0+k, 1); nan; Eu_indv(rFull0+k, 2)], ...        % byp8
    [Eu_indv(rDesc0+k, 2); Eu_indv(rSpar0+k, 2); Eu_indv(rFull0+k, 3)], ... % ut1
    [Eu_indv(rDesc0+k, 3); Eu_indv(rSpar0+k, 3); Eu_indv(rFull0+k, 4)], ... % ut2
    [Eu_indv(rDesc0+k, 4); Eu_indv(rSpar0+k, 4); nan] ...         % ut3
];

Eu_pert_b = mkEuPert(1);
Eu_pert_c = mkEuPert(2);
Eu_pert_d = mkEuPert(3);

 T_Eu_a = table( ...
    ctrl', ...
    Eu_pert_a(:,1), ...
    Eu_pert_a(:,2), ...
    Eu_pert_a(:,3), ...
    Eu_pert_a(:,4), ...
    Eu_pert_a(:,5), ...
    Eu_pert_a(:,6), ...
    'VariableNames', {'Ctrl','u2','u5','u8','fcu1','fcu2','fhu2'})
 T_Eu_b = table( ...
    ctrl', ...
    Eu_pert_b(:,1), ...
    Eu_pert_b(:,2), ...
    Eu_pert_b(:,3), ...
    Eu_pert_b(:,4), ...
    Eu_pert_b(:,5), ...
    Eu_pert_b(:,6), ...
    'VariableNames', {'Ctrl','u2','u5','u8','fcu1','fcu2','fhu2'})
 T_Eu_c = table( ...
    ctrl', ...
    Eu_pert_c(:,1), ...
    Eu_pert_c(:,2), ...
    Eu_pert_c(:,3), ...
    Eu_pert_c(:,4), ...
    Eu_pert_c(:,5), ...
    Eu_pert_c(:,6), ...
    'VariableNames', {'Ctrl','u2','u5','u8','fcu1','fcu2','fhu2'})
 T_Eu_d = table( ...
    ctrl', ...
    Eu_pert_d(:,1), ...
    Eu_pert_d(:,2), ...
    Eu_pert_d(:,3), ...
    Eu_pert_d(:,4), ...
    Eu_pert_d(:,5), ...
    Eu_pert_d(:,6), ...
    'VariableNames', {'Ctrl','u2','u5','u8','fcu1','fcu2','fhu2'})

end

writetable(T_Eu_a, 'tabla_RIC_Eu.xlsx', 'Sheet', 'Eu_pert_a')
writetable(T_Eu_b, 'tabla_RIC_Eu.xlsx', 'Sheet', 'Eu_pert_b')
writetable(T_Eu_c, 'tabla_RIC_Eu.xlsx', 'Sheet', 'Eu_pert_c')
writetable(T_Eu_d, 'tabla_RIC_Eu.xlsx', 'Sheet', 'Eu_pert_d')

%% EIP

[IAE_pert_a, IAE_pert_b, IAE_pert_c, IAE_pert_d] = IAE_pert{:};
EIP_a=[nan(1,4); ...
      (IAE_pert_a(1,:) - IAE_pert_a(2,:))*100./IAE_pert_a(1,:); ...
      (IAE_pert_a(1,:) - IAE_pert_a(3,:))*100./IAE_pert_a(1,:)]
EIP_b=[nan(1,4); ...
      (IAE_pert_b(1,:) - IAE_pert_b(2,:))*100./IAE_pert_b(1,:); ...
      (IAE_pert_b(1,:) - IAE_pert_b(3,:))*100./IAE_pert_b(1,:)]
EIP_c=[nan(1,4); ...
      (IAE_pert_c(1,:) - IAE_pert_c(2,:))*100./IAE_pert_c(1,:); ...
      (IAE_pert_c(1,:) - IAE_pert_c(3,:))*100./IAE_pert_c(1,:)]
EIP_d=[nan(1,4); ...
      (IAE_pert_d(1,:) - IAE_pert_d(2,:))*100./IAE_pert_d(1,:); ...
      (IAE_pert_d(1,:) - IAE_pert_d(3,:))*100./IAE_pert_d(1,:)]
  
 T_EIP_a = table( ...
    ctrl', ...
    EIP_a(:,1), ...
    EIP_a(:,2), ...
    EIP_a(:,3), ...
    EIP_a(:,4), ...
    'VariableNames', {'Ctrl','EIP % y1','EIP % y2','EIP % y3','EIP % y4'})
 T_EIP_b = table( ...
    ctrl', ...
    EIP_b(:,1), ...
    EIP_b(:,2), ...
    EIP_b(:,3), ...
    EIP_b(:,4), ...
    'VariableNames', {'Ctrl','EIP % y1','EIP % y2','EIP % y3','EIP % y4'})
 T_EIP_c = table( ...
    ctrl', ...
    EIP_c(:,1), ...
    EIP_c(:,2), ...
    EIP_c(:,3), ...
    EIP_c(:,4), ...
    'VariableNames', {'Ctrl','EIP % y1','EIP % y2','EIP % y3','EIP % y4'})
 T_EIP_d = table( ...
    ctrl', ...
    EIP_d(:,1), ...
    EIP_d(:,2), ...
    EIP_d(:,3), ...
    EIP_d(:,4), ...
    'VariableNames', {'Ctrl','EIP % y1','EIP % y2','EIP % y3','EIP % y4'})

writetable(T_EIP_a, 'tabla_RIC_EIP.xlsx', 'Sheet', 'EIP_pert_a')
writetable(T_EIP_b, 'tabla_RIC_EIP.xlsx', 'Sheet', 'EIP_pert_b')
writetable(T_EIP_c, 'tabla_RIC_EIP.xlsx', 'Sheet', 'EIP_pert_c')
writetable(T_EIP_d, 'tabla_RIC_EIP.xlsx', 'Sheet', 'EIP_pert_d')
